/**
 * LaTeX Symbol Definitions
 * Contains common mathematical symbols and their LaTeX codes
 */

// Export to window for plugin access
window.latexSymbols = {
    'Greek Letters': [
        { symbol: '\\alpha', code: '\\alpha', name: 'Alpha' },
        { symbol: '\\beta', code: '\\beta', name: 'Beta' },
        { symbol: '\\gamma', code: '\\gamma', name: 'Gamma' },
        { symbol: '\\delta', code: '\\delta', name: 'Delta' },
        { symbol: '\\epsilon', code: '\\epsilon', name: 'Epsilon' },
        { symbol: '\\zeta', code: '\\zeta', name: 'Zeta' },
        { symbol: '\\eta', code: '\\eta', name: 'Eta' },
        { symbol: '\\theta', code: '\\theta', name: 'Theta' },
        { symbol: '\\iota', code: '\\iota', name: 'Iota' },
        { symbol: '\\kappa', code: '\\kappa', name: 'Kappa' },
        { symbol: '\\lambda', code: '\\lambda', name: 'Lambda' },
        { symbol: '\\mu', code: '\\mu', name: 'Mu' },
        { symbol: '\\nu', code: '\\nu', name: 'Nu' },
        { symbol: '\\xi', code: '\\xi', name: 'Xi' },
        { symbol: '\\omicron', code: '\\omicron', name: 'Omicron' },
        { symbol: '\\pi', code: '\\pi', name: 'Pi' },
        { symbol: '\\rho', code: '\\rho', name: 'Rho' },
        { symbol: '\\sigma', code: '\\sigma', name: 'Sigma' },
        { symbol: '\\tau', code: '\\tau', name: 'Tau' },
        { symbol: '\\upsilon', code: '\\upsilon', name: 'Upsilon' },
        { symbol: '\\phi', code: '\\phi', name: 'Phi' },
        { symbol: '\\chi', code: '\\chi', name: 'Chi' },
        { symbol: '\\psi', code: '\\psi', name: 'Psi' },
        { symbol: '\\omega', code: '\\omega', name: 'Omega' },
        { symbol: '\\mathrm{A}', code: '\\mathrm{A}', name: 'Alpha (capital)' },
        { symbol: '\\mathrm{B}', code: '\\mathrm{B}', name: 'Beta (capital)' },
        { symbol: '\\Gamma', code: '\\Gamma', name: 'Gamma (capital)' },
        { symbol: '\\Delta', code: '\\Delta', name: 'Delta (capital)' },
        { symbol: '\\mathrm{E}', code: '\\mathrm{E}', name: 'Epsilon (capital)'},
        { symbol: '\\mathrm{Z}', code: '\\mathrm{Z}', name: 'Zeta (capital)'},
        { symbol: '\\mathrm{H}', code: '\\mathrm{H}', name: 'Eta (capital)'},
        { symbol: '\\Theta', code: '\\Theta', name: 'Theta (capital)' },
        { symbol: '\\mathrm{I}', code: '\\mathrm{I}', name: 'Iota (capital)'},
        { symbol: '\\mathrm{K}', code: '\\mathrm{K}', name: 'Kappa (capital)'},
        { symbol: 'Λ', code: '\\Lambda', name: 'Lambda (capital)' },
        { symbol: '\\mathrm{M}', code: '\\mathrm{M}', name: 'Mu (capital)'},
        { symbol: '\\mathrm{N}', code: '\\mathrm{N}', name: 'Nu (capital)'},
        { symbol: 'Ξ', code: '\\Xi', name: 'Xi (capital)' },
        { symbol: '\\mathrm{O}', code: '\\mathrm{O}', name: 'Omicron (capital)'},
        { symbol: '\\Pi', code: '\\Pi', name: 'Pi (capital)' },
        { symbol: '\\Sigma', code: '\\Sigma', name: 'Sigma (capital)' },
        { symbol: 'Φ', code: '\\Phi', name: 'Phi (capital)' },
        { symbol: 'Ψ', code: '\\Psi', name: 'Psi (capital)' },
        { symbol: 'Ω', code: '\\Omega', name: 'Omega (capital)' }
    ],
    'Operators': [
        { symbol: '\\pm', code: '\\pm', name: 'Plus-minus' },
        { symbol: '\\mp', code: '\\mp', name: 'Minus-plus' },
        { symbol: '\\times', code: '\\times', name: 'Times' },
        { symbol: '\\div', code: '\\div', name: 'Division' },
        { symbol: '\\cdot', code: '\\cdot', name: 'Dot' },
        { symbol: '\\circ', code: '\\circ', name: 'Circle' },
        { symbol: '\\ast', code: '\\ast', name: 'Asterisk' },
        { symbol: '\\star', code: '\\star', name: 'Star' },
        { symbol: '\\cap', code: '\\cap', name: 'Intersection' },
        { symbol: '\\cup', code: '\\cup', name: 'Union' },
        { symbol: '\\subset', code: '\\subset', name: 'Subset' },
        { symbol: '\\supset', code: '\\supset', name: 'Superset' },
        { symbol: '\\in', code: '\\in', name: 'Element of' },
        { symbol: '\\notin', code: '\\notin', name: 'Not element of' },
        { symbol: '\\ni', code: '\\ni', name: 'Contains' },
        { symbol: '\\emptyset', code: '\\emptyset', name: 'Empty set' },
        { symbol: '\\forall', code: '\\forall', name: 'For all' },
        { symbol: '\\exists', code: '\\exists', name: 'Exists' },
        { symbol: '\\nexists', code: '\\nexists', name: 'Not exists' },
        { symbol: '\\nabla', code: '\\nabla', name: 'Nabla' },
        { symbol: '\\partial', code: '\\partial', name: 'Partial derivative' },
        { symbol: '\\infty', code: '\\infty', name: 'Infinity' },
        { symbol: '\\sum', code: '\\sum', name: 'Sum' },
        { symbol: '\\prod', code: '\\prod', name: 'Product' },
        { symbol: '\\int', code: '\\int', name: 'Integral' },
        { symbol: '\\oint', code: '\\oint', name: 'Contour integral' },
        { symbol: '\\iint', code: '\\iint', name: 'Double integral' },
        { symbol: '\\iiint', code: '\\iiint', name: 'Triple integral' },
        { symbol: '\\iiiint', code: '\\iiiint', name: 'Quadruple integral' },
        { symbol: '\\oiint', code: '\\oiint', name: 'Surface integral' },
        { symbol: '\\oiiint', code: '\\oiiint', name: 'Volume integral' }
    ],
    'Relations': [
        { symbol: '=', code: '=', name: 'Equals' },
        { symbol: '\\neq', code: '\\neq', name: 'Not equals' },
        { symbol: '\\approx', code: '\\approx', name: 'Approximately' },
        { symbol: '\\equiv', code: '\\equiv', name: 'Equivalent' },
        { symbol: '\\leq', code: '\\leq', name: 'Less than or equal' },
        { symbol: '\\geq', code: '\\geq', name: 'Greater than or equal' },
        { symbol: '\\lt', code: '\\lt', name: 'Less than' },
        { symbol: '\\gt', code: '\\gt', name: 'Greater than' },
        { symbol: '\\ll', code: '\\ll', name: 'Much less than' },
        { symbol: '\\gg', code: '\\gg', name: 'Much greater than' },
        { symbol: '\\prec', code: '\\prec', name: 'Precedes' },
        { symbol: '\\succ', code: '\\succ', name: 'Succeeds' },
        { symbol: '\\preceq', code: '\\preceq', name: 'Precedes or equal' },
        { symbol: '\\succeq', code: '\\succeq', name: 'Succeeds or equal' },
        { symbol: '\\sim', code: '\\sim', name: 'Similar to' },
        { symbol: '\\simeq', code: '\\simeq', name: 'Asymptotically equal' },
        { symbol: '\\cong', code: '\\cong', name: 'Congruent' },
        { symbol: '\\propto', code: '\\propto', name: 'Proportional to' },
        { symbol: '\\perp', code: '\\perp', name: 'Perpendicular' },
        { symbol: '\\parallel', code: '\\parallel', name: 'Parallel' },
        { symbol: '\\vdash', code: '\\vdash', name: 'Proves' },
        { symbol: '\\models', code: '\\models', name: 'Models' }
    ],
    'Arrows': [
        { symbol: '\\leftarrow', code: '\\leftarrow', name: 'Left arrow' },
        { symbol: '\\rightarrow', code: '\\rightarrow', name: 'Right arrow' },
        { symbol: '\\leftrightarrow', code: '\\leftrightarrow', name: 'Left-right arrow' },
        { symbol: '\\Leftarrow', code: '\\Leftarrow', name: 'Left double arrow' },
        { symbol: '\\Rightarrow', code: '\\Rightarrow', name: 'Right double arrow' },
        { symbol: '\\Leftrightarrow', code: '\\Leftrightarrow', name: 'Left-right double arrow' },
        { symbol: '\\uparrow', code: '\\uparrow', name: 'Up arrow' },
        { symbol: '\\downarrow', code: '\\downarrow', name: 'Down arrow' },
        { symbol: '\\updownarrow', code: '\\updownarrow', name: 'Up-down arrow' },
        { symbol: '\\Uparrow', code: '\\Uparrow', name: 'Up double arrow' },
        { symbol: '\\Downarrow', code: '\\Downarrow', name: 'Down double arrow' },
        { symbol: '\\Updownarrow', code: '\\Updownarrow', name: 'Up-down double arrow' },
        { symbol: '\\nearrow', code: '\\nearrow', name: 'Northeast arrow' },
        { symbol: '\\searrow', code: '\\searrow', name: 'Southeast arrow' },
        { symbol: '\\swarrow', code: '\\swarrow', name: 'Southwest arrow' },
        { symbol: '\\nwarrow', code: '\\nwarrow', name: 'Northwest arrow' }
    ],
    'Delimiters': [
        { symbol: '(', code: '(', name: 'Left parenthesis' },
        { symbol: ')', code: ')', name: 'Right parenthesis' },
        { symbol: '[', code: '[', name: 'Left bracket' },
        { symbol: ']', code: ']', name: 'Right bracket' },
        { symbol: '\\{', code: '\\{', name: 'Left brace' },
        { symbol: '\\}', code: '\\}', name: 'Right brace' },
        { symbol: '|', code: '|', name: 'Vertical bar' },
        { symbol: '\\lfloor', code: '\\lfloor', name: 'Left floor' },
        { symbol: '\\rfloor', code: '\\rfloor', name: 'Right floor' },
        { symbol: '\\lceil', code: '\\lceil', name: 'Left ceiling' },
        { symbol: '\\rceil', code: '\\rceil', name: 'Right ceiling' },
        { symbol: '\\langle', code: '\\langle', name: 'Left angle' },
        { symbol: '\\rangle', code: '\\rangle', name: 'Right angle' }
    ],
    'Accents': [
        { symbol: '\\acute{}', code: '\\acute{}', name: 'Acute accent' },
        { symbol: '\\grave{}', code: '\\grave{}', name: 'Grave accent' },
        { symbol: '\\hat{}', code: '\\hat{}', name: 'Hat' },
        { symbol: '\\ddot{}', code: '\\ddot{}', name: 'Diaeresis' },
        { symbol: '\\tilde{}', code: '\\tilde{}', name: 'Tilde' },
        { symbol: '\\bar{}', code: '\\bar{}', name: 'Bar' },
        { symbol: '\\breve{}', code: '\\breve{}', name: 'Breve' },
        { symbol: '\\check{}', code: '\\check{}', name: 'Check' },
        { symbol: '\\dot{}', code: '\\dot{}', name: 'Dot' },
        { symbol: '\\vec{}', code: '\\vec{}', name: 'Vector' }
    ],
    'Functions': [
        { symbol: '\\sin', code: '\\sin', name: 'Sine' },
        { symbol: '\\cos', code: '\\cos', name: 'Cosine' },
        { symbol: '\\tan', code: '\\tan', name: 'Tangent' },
        { symbol: '\\cot', code: '\\cot', name: 'Cotangent' },
        { symbol: 'sec', code: '\\sec', name: 'Secant' },
        { symbol: '\\csc', code: '\\csc', name: 'Cosecant' },
        { symbol: 'arcsin', code: '\\arcsin', name: 'Arcsine' },
        { symbol: '\\arccos', code: '\\arccos', name: 'Arccosine' },
        { symbol: 'arctan', code: '\\arctan', name: 'Arctangent' },
        { symbol: '\\sinh', code: '\\sinh', name: 'Hyperbolic sine' },
        { symbol: 'cosh', code: '\\cosh', name: 'Hyperbolic cosine' },
        { symbol: '\\tanh', code: '\\tanh', name: 'Hyperbolic tangent' },
        { symbol: 'log', code: '\\log', name: 'Logarithm' },
        { symbol: '\\ln', code: '\\ln', name: 'Natural logarithm' },
        { symbol: '\\lg', code: '\\lg', name: 'Base 10 logarithm' },
        { symbol: 'exp', code: '\\exp', name: 'Exponential' },
        { symbol: '\\min', code: '\\min', name: 'Minimum' },
        { symbol: '\\max', code: '\\max', name: 'Maximum' },
        { symbol: '\\sup', code: '\\sup', name: 'Supremum' },
        { symbol: '\\inf', code: '\\inf', name: 'Infimum' },
        { symbol: '\\gcd', code: '\\gcd', name: 'Greatest common divisor' },
        { symbol: '\\det', code: '\\det', name: 'Determinant' },
        { symbol: '\\dim', code: '\\dim', name: 'Dimension' },
        { symbol: '\\ker', code: '\\ker', name: 'Kernel' },
        { symbol: '\\deg', code: '\\deg', name: 'Degree' },
        { symbol: '\\hom', code: '\\hom', name: 'Homomorphism' },
        { symbol: '\\arg', code: '\\arg', name: 'Argument' }
    ],
    'Math Structures': [
        { symbol: '\\frac{x}{y}', code: '\\frac{}{}', name: 'Fraction' },
        { symbol: '\\sqrt{x}', code: '\\sqrt{}', name: 'Square root' },
        { symbol: '\\sqrt[n]{x}', code: '\\sqrt[n]{x}', name: 'Nth root' },
        { symbol: 'x^{y}', code: 'x^{y}', name: 'Superscript' },
        { symbol: 'x_{y}', code: 'x_{y}', name: 'Subscript' },
        
        { symbol: '\\int', code: '\\int', name: 'Integral' },
        { symbol: '\\int_{x}^{y}', code: '\\int_{x}^{y}', name: 'Integral with limits' },
        
        { symbol: '\\sum', code: '\\sum', name: 'Sum' },
        { symbol: '\\sum_{x}^{y}', code: '\\sum_{x}^{y}', name: 'Sum with limits' },
        
        { symbol: '\\prod', code: '\\prod', name: 'Product' },
        { symbol: '\\prod_{x}^{y}', code: '\\prod_{x}^{y}', name: 'Product with limits' },
        
        { symbol: '\\lim_{x \\to \\infty}', code: '\\lim_{x \\to \\infty}', name: 'Limit to infinity' },
        
        { symbol: '(x)', code: '(x)', name: 'Parentheses (auto-size)' },
        { symbol: '[x]', code: '[x]', name: 'Brackets (auto-size)' },
        { symbol: '\\{x\\}', code: '\\{x\\}', name: 'Braces (auto-size)' },
        { symbol: '|x|', code: '|x|', name: 'Absolute value' },
        
        { symbol: '\\begin{pmatrix} x & y \\\\ z & t \\end{pmatrix}', code: '\\begin{pmatrix} x & y \\\\ z & t \\end{pmatrix}', name: 'Matrix (parentheses)' },
        { symbol: '\\begin{bmatrix} x & y \\\\ z & t \\end{bmatrix}', code: '\\begin{bmatrix} x & y \\\\ z & t \\end{bmatrix}', name: 'Matrix (brackets)' },
        { symbol: '\\begin{cases} x \\\\ y \\end{cases}', code: '\\begin{cases} x \\\\ y \\end{cases}', name: 'Cases' },
        { symbol: '\\begin{aligned} x \\\\ y \\end{aligned}', code: '\\begin{aligned} x \\\\ y \\end{aligned}', name: 'Aligned environment' },
        { symbol: '\\begin{array}{cc} x & y \\\\ z & t \\end{array}', code: '\\begin{array}{cc} x & y \\\\ z & t \\end{array}', name: 'Array' }
    ],
    'Miscellaneous': [
        { symbol: '\\angle', code: '\\angle', name: 'Angle' },
        { symbol: '^{\\circ}', code: '^{\\circ}', name: 'Degree' },
        { symbol: '\\prime', code: '\\prime', name: 'Prime' },
        { symbol: '\\ldots', code: '\\ldots', name: 'Ellipsis' },
        { symbol: '\\cdots', code: '\\cdots', name: 'Centered ellipsis' },
        { symbol: '\\vdots', code: '\\vdots', name: 'Vertical ellipsis' },
        { symbol: '\\ddots', code: '\\ddots', name: 'Diagonal ellipsis' },
        { symbol: '\\aleph', code: '\\aleph', name: 'Aleph' },
        { symbol: '\\hbar', code: '\\hbar', name: 'H-bar' },
        { symbol: '\\Im', code: '\\Im', name: 'Imaginary part' },
        { symbol: '\\Re', code: '\\Re', name: 'Real part' },
        { symbol: '\\ell', code: '\\ell', name: 'Ell' },
        { symbol: '\\wp', code: '\\wp', name: 'Weierstrass p' },
        { symbol: '\\spadesuit', code: '\\spadesuit', name: 'Spades' },
        { symbol: '\\clubsuit', code: '\\clubsuit', name: 'Clubs' },
        { symbol: '\\heartsuit', code: '\\heartsuit', name: 'Hearts' },
        { symbol: '\\diamondsuit', code: '\\diamondsuit', name: 'Diamonds' }
    ],
    'Chemical Symbols': [
        { symbol: '\\ce{H2O}', code: '\\ce{H2O}', name: 'Water' },
        { symbol: '\\ce{CO2}', code: '\\ce{CO2}', name: 'Carbon dioxide' },
        { symbol: '\\ce{NaCl}', code: '\\ce{NaCl}', name: 'Sodium chloride' },
        { symbol: '\\ce{H2SO4}', code: '\\ce{H2SO4}', name: 'Sulfuric acid' },
        { symbol: '\\ce{NH3}', code: '\\ce{NH3}', name: 'Ammonia' },
        { symbol: '\\ce{CH4}', code: '\\ce{CH4}', name: 'Methane' },
        { symbol: '\\ce{C6H12O6}', code: '\\ce{C6H12O6}', name: 'Glucose' },
        { symbol: '\\ce{H+}', code: '\\ce{H+}', name: 'Hydrogen ion' },
        { symbol: '\\ce{OH-}', code: '\\ce{OH-}', name: 'Hydroxide ion' },
        { symbol: '\\ce{Fe^{2+}}', code: '\\ce{Fe^{2+}}', name: 'Iron(II) ion' },
        { symbol: '\\ce{Fe^{3+}}', code: '\\ce{Fe^{3+}}', name: 'Iron(III) ion' },
        { symbol: '\\ce{SO4^{2-}}', code: '\\ce{SO4^{2-}}', name: 'Sulfate ion' },
        { symbol: '\\ce{NO3-}', code: '\\ce{NO3-}', name: 'Nitrate ion' },
        { symbol: '\\ce{CO3^{2-}}', code: '\\ce{CO3^{2-}}', name: 'Carbonate ion' },
        { symbol: '\\ce{PO4^{3-}}', code: '\\ce{PO4^{3-}}', name: 'Phosphate ion' },
        { symbol: '\\ce{H2O -> H+ + OH-}', code: '\\ce{H2O -> H+ + OH-}', name: 'Water dissociation' },
        { symbol: '\\ce{2H2 + O2 -> 2H2O}', code: '\\ce{2H2 + O2 -> 2H2O}', name: 'Water formation' },
        { symbol: '\\ce{CaCO3 <=> Ca^{2+} + CO3^{2-}}', code: '\\ce{CaCO3 <=> Ca^{2+} + CO3^{2-}}', name: 'Equilibrium reaction' },
        { symbol: '\\ce{CH3COOH}', code: '\\ce{CH3COOH}', name: 'Acetic acid' },
        { symbol: '\\ce{C2H5OH}', code: '\\ce{C2H5OH}', name: 'Ethanol' },
        { symbol: '\\ce{NH4+}', code: '\\ce{NH4+}', name: 'Ammonium ion' },
        { symbol: '\\ce{CuSO4}', code: '\\ce{CuSO4}', name: 'Copper sulfate' },
        { symbol: '\\ce{NaOH}', code: '\\ce{NaOH}', name: 'Sodium hydroxide' },
        { symbol: '\\ce{HCl}', code: '\\ce{HCl}', name: 'Hydrochloric acid' },
        { symbol: '\\ce{HNO3}', code: '\\ce{HNO3}', name: 'Nitric acid' },
        { symbol: '\\ce{KMnO4}', code: '\\ce{KMnO4}', name: 'Potassium permanganate' },
        { symbol: '\\ce{Al2O3}', code: '\\ce{Al2O3}', name: 'Aluminum oxide' },
        { symbol: '\\ce{Fe2O3}', code: '\\ce{Fe2O3}', name: 'Iron(III) oxide' },
        { symbol: '\\ce{Ca(OH)2}', code: '\\ce{Ca(OH)2}', name: 'Calcium hydroxide' },
        { symbol: '\\ce{MgCl2}', code: '\\ce{MgCl2}', name: 'Magnesium chloride' }
    ]
};
