<?php
/*
      +----------------------------------------------------------------------+
      | CLAROLINE version 1.3.0 $Revision$                               |
      +----------------------------------------------------------------------+
      | Copyright (c) 2001, 2002 Universite catholique de Louvain (UCL)      |
      +----------------------------------------------------------------------+
      |   $Id$           |
      |   English Translation                                                |
      +----------------------------------------------------------------------+
      |   This program is free software; you can redistribute it and/or      |
      |   modify it under the terms of the GNU General Public License        |
      |   as published by the Free Software Foundation; either version 2     |
      |   of the License, or (at your option) any later version.             |
      |                                                                      |
      |   This program is distributed in the hope that it will be useful,    |
      |   but WITHOUT ANY WARRANTY; without even the implied warranty of     |
      |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the      |
      |   GNU General Public License for more details.                       |
      |                                                                      |
      |   You should have received a copy of the GNU General Public License  |
      |   along with this program; if not, write to the Free Software        |
      |   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA          |
      |   02111-1307, USA. The GNU GPL license is also available through     |
      |   the world-wide-web at http://www.gnu.org/copyleft/gpl.html         |
      +----------------------------------------------------------------------+
      | Authors: Thomas Depraetere <depraetere@ipm.ucl.ac.be>                |
      |          Hugues Peeters    <peeters@ipm.ucl.ac.be>                   |
      |          Christophe Geschι <gesche@ipm.ucl.ac.be>                    |
      +----------------------------------------------------------------------+
      | Translator :                                                         |
      |          Thomas Depraetere <depraetere@ipm.ucl.ac.be>                |
      |          Andrew Lynn       <Andrew.Lynn@strath.ac.uk>                |
      +----------------------------------------------------------------------+
 */

$langInvalidId = '<font color="red" size="1" face="arial, helvetica">
	Login failed.<br>If you are not registered, create a new account
	using the <a href=claroline/auth/newuser_info.php>registration form</a>.
	</font><br>&nbsp;<br>';
$langMyCourses="My courses";
$langMyCoursesProf="My courses (Professors)";
$langMyCoursesUser="My registered courses (Student)";

$langNoCourses="There are no courses";

$langCourseCreate="Create course site";
$langModifyProfile="Modify my profile";
$langMyAgenda = "My Agenda";
$langMyAnnouncements = "My Announcements";

$langWelcome="courses are freely available below. Other  courses require 
a username and a password, which you can obtain by clicking on 'registration'. Professors
can create course websites clicking on registration too, but selecting then 'Create course site'.";
$langAdminTool = "Admin Tool";
$langUserName="Username";
$langPass="Password";
$langEnter="Enter";
$langHelp="Help";
$langManager="Manager";
$langPlatform="Powered by";
$langReg="Registration";
$langMenu ="Menu";
$langLogout="Logout";
$langOtherCourses="Courses list";
$langSupportForum="Support forum";
$langNewUser = 'New user registration';
$langProfReq = 'Professor account request';
$langUser = 'User';
$langManuals = 'Available manuals';
$langContact = 'Contact';
$lang_forgot_pass = 'Forgot your password?';
$langNewAnnounce = "New !";
$langUnregUser = "Unregister";
$langListFaculte = "Faculte";
$langInfoPlat = "Platform infornation";

$langInfo = "<b>GUNet e-Class</b> platform is a ... <b>edit /lang/english/index.inc and fix this!!</b> είναι ένα ολοκληρωμένο Σύστημα Διαχείρισης Ηλεκτρονικών Μαθημάτων και αποτελεί την πρόταση του Ακαδημαϊκού Διαδικτύου για την υποστήριξη της 
Υπηρεσίας Ασύγχρονης Τηλεκπαίδευσης. Έχει σχεδιαστεί με προσανατολισμό την ενίσχυση 
της κλασσικής διδασκαλίας και είναι προσαρμοσμένη στις ανάγκες τις τριτοβάθμιας εκπαίδευσης. 
Υποστηρίζεται κεντρικά από το GUnet και διανέμεται ελεύθερα σε όλα τα Ακαδημαϊκά Ιδρύματα της χώρας. 
Πληροφορίες για τη λειτουργία της πλατφόρμας μπορείτε να βρείτε στα διαθέσιμα εγχειρίδια.";
?>
