<!-- HEADER BEGIN -->
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<style type="text/css">
body 
{
	font-family : 'Times New Roman',times,serif ;
	font-size :; 
	background-color:white ;
}
#header
{
	color: #666666;
	font-family : 'Times New Roman',times,serif ;
	font-weight: bold;
	font-variant: small-caps;
	background-color:#FFFFFF;
	font-size: 1.4em;
	padding: 2px;
	margin-bottom: 5px;
	text-align : center;
	border-bottom: 2px dotted #888;
}
#footer
{
	position : relative;
	top : 0.5em;
	border-top: 2px dotted #888;
	text-align: center;
	font-size: .8em;
	font-family :  'Times New Roman',times,serif ;
	padding: 2px;
	clear: both;
}
</style>
</head>
<body>
<div id="header">Header (see header.inc)</div>
<!-- HEADER END -->
