phpCAS: CASClient Class Reference
CASClient Class Reference
Public Member Functions
setHTMLHeader ($header)
setHTMLFooter ($footer)
setNoExitOnAuthError ()
setNoClearTicketsFromUrl ()
setPostAuthenticateCallback ($function, array $additionalArgs=array())
setSingleSignoutCallback ($function, array $additionalArgs=array())
setLang ($lang)
getServerLoginURL ($gateway=false, $renew=false)
setServerLoginURL ($url)
setServerServiceValidateURL ($url)
setServerProxyValidateURL ($url)
setServerSamlValidateURL ($url)
getServerServiceValidateURL ()
getServerSamlValidateURL ()
getServerProxyValidateURL ()
getServerProxyURL ()
getServerLogoutURL ()
setServerLogoutURL ($url)
setExtraCurlOption ($key, $value)
setRequestImplementation ($className)
CASClient ($server_version, $proxy, $server_hostname, $server_port, $server_uri, $start_session=true)
getStartSession ($session)
getUser ()
setAttributes ($attributes)
getAttributes ()
hasAttributes ()
hasAttribute ($key)
getAttribute ($key)
renewAuthentication ()
forceAuthentication ()
setCacheTimesForAuthRecheck ($n)
checkAuthentication ()
isAuthenticated ()
isSessionAuthenticated ()
redirectToCas ($gateway=false, $renew=false)
logout ($params)
handleLogoutRequests ($check_client=true, $allowed_clients=false)
getST ()
setST ($st)
hasST ()
setCasServerCACert ($cert)
setNoCasServerValidation ()
validateST ($validate_url, &$text_response, &$tree_response)
validateSA ($validate_url, &$text_response, &$tree_response)
isProxy ()
setCallbackURL ($url)
setPGTStorageFile ($format='', $path='')
_curl_read_headers ($ch, $header)
serviceWeb ($url, &$err_code, &$output)
serviceMail ($url, $service, $flags, &$err_code, &$err_msg, &$pt)
getPT ()
setPT ($pt)
hasPT ()
getProxies ()
getSA ()
setSA ($sa)
hasSA ()
validatePT (&$validate_url, &$text_response, &$tree_response)
setURL ($url)
Private Member Functions
HTMLFilterOutput ($str)
printHTMLHeader ($title)
printHTMLFooter ()
getLang ()
getString ($str)
getServerVersion ()
getServerHostname ()
getServerPort ()
getServerURI ()
getServerBaseURL ()
isHttps ()
setStartSession ($session)
renameSession ($ticket)
setUser ($user)
wasPreviouslyAuthenticated ()
isLogoutRequest ()
readExtraAttributesCas20 ($success_elements)
addAttributeToArray (array &$attributeArray, $name, $value)
setSessionAttributes ($text_response)
getPGT ()
setPGT ($pgt)
hasPGT ()
setCallbackMode ($callback_mode)
isCallbackMode ()
getCallbackURL ()
callback ()
initPGTStorage ()
storePGT ($pgt, $pgt_iou)
loadPGT ($pgt_iou)
validatePGT (&$validate_url, $text_response, $tree_response)
retrievePT ($target_service, &$err_code, &$err_msg)
readURL ($url, array $cookies, &$headers, &$body, &$err_msg)
buildSAMLPayload ()
setProxies ($proxies)
getURL ()
getServerUrl ()
removeParameterFromQueryString ($parameterName, $queryString)
authError ($failure, $cas_url, $no_response, $bad_response='', $cas_response='', $err_code='', $err_msg='')
Private Attributes
$_output_header
$_output_footer
$_exitOnAuthError = true
$_clearTicketsFromUrl = true
$_postAuthenticateCallbackFunction = null
$_postAuthenticateCallbackArgs = array()
$_signoutCallbackFunction = null
$_signoutCallbackArgs = array()
$_lang
$_strings
$_server
$_curl_options = array()
$_requestImplementation = 'CAS_CurlRequest'
$_start_session
$_user
$_attributes
$_cache_times_for_auth_recheck
$_st
$_cas_server_ca_cert
$_no_cas_server_validation
$_proxy
$_serviceCookieJar
$_pgt
$_callback_mode
$_callback_url
$_pgt_storage
$_curl_headers = array()
$_pt
$_proxies = array()
$_url
Detailed Description
The CASClient class is a client interface that provides CAS authentication to PHP applications.
Author:
Pascal Aubry <pascal.aubry at univ-rennes1.fr>
Definition at line 57 of file client.php.
Member Function Documentation
CASClient::getStartSession ($ session)
Definition at line 808 of file client.php.
CASClient::renameSession ($ ticket) [private]
Renaming the session
Definition at line 816 of file client.php.
References phpCAS::error(), phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceEnd().
CASClient::setStartSession ($ session) [private]
Definition at line 803 of file client.php.
Member Data Documentation
CASClient::$_start_session [private]
A variable to whether phpcas will use its own session handling. Default = true
Definition at line 801 of file client.php.