phpCAS: docs/examples/config.php File Reference
docs/examples/config.php File Reference
Variables
$phpcas_path = '../../source/'
$cas_host = '192.168.178.254'
$cas_context = '/cas'
$cas_port = 8443
$cas_server_ca_cert_path = '/usr/local/share/ca-certificates/3some-cacert.crt'
$cas_real_hosts
$db = 'mysql:host=localhost;dbname=phpcas'
$db_user = 'root'
$db_password = 'test1234'
$db_table = 'phpcas'
$curdir = "/"
$serviceUrl = $curbase.$curdir.'example_service.php'
$serviceUrl2 = $curbase.$curdir.'example_service_that_proxies.php'
$cas_url = 'https://'.$cas_host
Variable Documentation
$cas_context = '/cas'
Examples:
example_advanced_saml11.php, example_custom_urls.php, example_gateway.php, example_html.php, example_lang.php, example_logout.php, example_pgt_storage_file.php, example_proxy_GET.php, example_proxy_POST.php, example_proxy_serviceWeb.php, example_proxy_serviceWeb_chaining.php, example_service.php, example_service_POST.php, example_service_that_proxies.php, and example_simple.php.
Definition at line 16 of file config.php.
$cas_host = '192.168.178.254'
Examples:
example_advanced_saml11.php, example_custom_urls.php, example_gateway.php, example_html.php, example_lang.php, example_logout.php, example_pgt_storage_file.php, example_proxy_GET.php, example_proxy_POST.php, example_proxy_serviceWeb.php, example_proxy_serviceWeb_chaining.php, example_service.php, example_service_POST.php, example_service_that_proxies.php, and example_simple.php.
Definition at line 13 of file config.php.
$cas_port = 8443
Examples:
example_advanced_saml11.php, example_custom_urls.php, example_gateway.php, example_html.php, example_lang.php, example_logout.php, example_pgt_storage_file.php, example_proxy_GET.php, example_proxy_POST.php, example_proxy_serviceWeb.php, example_proxy_serviceWeb_chaining.php, example_service.php, example_service_POST.php, example_service_that_proxies.php, and example_simple.php.
Definition at line 19 of file config.php.
$cas_real_hosts
Initial value:
 array (
        '192.168.178.254'
)
Examples:
example_advanced_saml11.php.
Definition at line 30 of file config.php.
$cas_server_ca_cert_path = '/usr/local/share/ca-certificates/3some-cacert.crt'
Examples:
example_advanced_saml11.php.
Definition at line 22 of file config.php.
if ($cas_port!= '443') $cas_url = 'https://'.$cas_host
Definition at line 63 of file config.php.
Referenced by CAS_Client::authError(), CAS_Client::logout(), CAS_Client::redirectToCas(), and CAS_Client::retrievePT().
$curdir = "/"
Definition at line 56 of file config.php.
$db = 'mysql:host=localhost;dbname=phpcas'
Definition at line 36 of file config.php.
$db_password = 'test1234'
Definition at line 40 of file config.php.
$db_table = 'phpcas'
Definition at line 41 of file config.php.
$db_user = 'root'
Definition at line 39 of file config.php.
$phpcas_path = '../../source/'
Examples:
example_advanced_saml11.php, example_custom_urls.php, example_gateway.php, example_html.php, example_lang.php, example_logout.php, example_pgt_storage_file.php, example_proxy_GET.php, example_proxy_POST.php, example_proxy_serviceWeb.php, example_proxy_serviceWeb_chaining.php, example_service.php, example_service_POST.php, example_service_that_proxies.php, and example_simple.php.
Definition at line 6 of file config.php.
$serviceUrl = $curbase.$curdir.'example_service.php'
Examples:
example_proxy_POST.php.
Definition at line 59 of file config.php.
Referenced by CAS_Client::serviceMail().
$serviceUrl2 = $curbase.$curdir.'example_service_that_proxies.php'
Definition at line 61 of file config.php.