phpCAS: Callback from the CAS server
Callback from the CAS server
[CAS Proxy features (CAS 2.0, Proxy Granting Tickets), CAS Basic client features (CAS 1.0, Service Tickets)]
Functions
CASClient::setCallbackMode ($callback_mode)
CASClient::isCallbackMode ()
CASClient::getCallbackURL ()
CASClient::setCallbackURL ($url)
CASClient::callback ()
Variables
CASClient::$_callback_mode
CASClient::$_callback_url
Function Documentation
CASClient::callback () [private, inherited]
This method is called by CASClient::CASClient() when running in callback mode. It stores the PGT and its PGT Iou, prints its output and halts.
Definition at line 2034 of file client.php.
References phpCAS::error(), phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceExit().
Referenced by CASClient::wasPreviouslyAuthenticated().
CASClient::getCallbackURL () [private, inherited]
This method returns the URL that should be used for the PGT callback (in fact the URL of the current request without any CGI parameter, except if phpCAS::setFixedCallbackURL() was used).
Returns:
The callback URL
Definition at line 2004 of file client.php.
Referenced by CASClient::validateST().
CASClient::isCallbackMode () [private, inherited]
This method returns TRUE when the CAs client is running i callback mode, FALSE otherwise.
Returns:
A boolean.
Definition at line 1983 of file client.php.
Referenced by CASClient::CASClient(), and CASClient::wasPreviouslyAuthenticated().
CASClient::setCallbackMode ($ callback_mode) [private, inherited]
This method sets/unsets callback mode.
Parameters:
$callback_mode TRUE to set callback mode, FALSE otherwise.
Definition at line 1972 of file client.php.
Referenced by CASClient::CASClient().
CASClient::setCallbackURL ($ url) [inherited]
This method sets the callback url.
Parameters:
$callback_url url to set callback
Definition at line 2025 of file client.php.
Variable Documentation
CASClient::$_callback_mode [private, inherited]
each PHP script using phpCAS in proxy mode is its own callback to get the PGT back from the CAS server. callback_mode is detected by the constructor thanks to the GET parameters. a boolean to know if the CAS client is running in callback mode. Written by CASClient::setCallBackMode(), read by CASClient::isCallbackMode().
Definition at line 1965 of file client.php.
CASClient::$_callback_url [private, inherited]
the URL that should be used for the PGT callback (in fact the URL of the current request without any CGI parameter). Written and read by CASClient::getCallbackURL().
Definition at line 1995 of file client.php.