phpCAS: Internationalization
Internationalization
[Configuration]
Files
file spanish.php
file english.php
file english.php
file german.php
file greek.php
file languages.php
file spanish.php
Enumerations
enum PHPCAS_LANG_DEFAULT
Functions
CAS_Client::getLang ()
CAS_Client::getString ($str)
CAS_Client::setLang ($lang)
Variables
CAS_Client::$_lang
CAS_Client::$_strings
Detailed Description
To add a new language:
1. define a new constant PHPCAS_LANG_XXXXXX in CAS/CAS.php
2. copy any file from CAS/languages to CAS/languages/XXXXXX.php
3. Make the translations
Enumeration Type Documentation
enum PHPCAS_LANG_DEFAULT
phpCAS default language (when phpCAS::setLang() is not used)
Definition at line 228 of file CAS.php.
Function Documentation
CAS_Client::getLang () [private, inherited]
This method returns the language used by phpCAS.
Returns:
a string representing the language
Definition at line 201 of file Client.php.
References CAS_Client::setLang().
Referenced by CAS_Client::getString().
CAS_Client::getString ($ str) [private, inherited]
This method returns a string depending on the language.
Parameters:
$str the index of the string in $_string.
Returns:
the string corresponding to $index in $string.
Definition at line 226 of file Client.php.
References _strings, and CAS_Client::getLang().
Referenced by CAS_Client::logout(), CAS_Client::printHTMLFooter(), and CAS_Client::redirectToCas().
CAS_Client::setLang ($ lang) [inherited]
This method is used to set the language used by phpCAS.
Note:
Can be called only once.
Parameters:
$lang a string representing the language.
See also:
CAS_LANG_FRENCH, CAS_LANG_ENGLISH
Definition at line 245 of file Client.php.
References _strings.
Referenced by CAS_Client::getLang().
Variable Documentation
CAS_Client::$_lang [private, inherited]
A string corresponding to the language used by phpCAS. Written by CAS_Client::setLang(), read by CAS_Client::getLang().
Note:
debugging information is always in english (debug purposes only).
See also:
CAS_Client::_strings, CAS_Client::getString()
Definition at line 194 of file Client.php.
CAS_Client::$_strings [private, inherited]
array containing the strings used by phpCAS. Written by CAS_Client::setLang(), read by CAS_Client::getString() and used by CAS_Client::setLang().
Note:
This array is filled by instructions in CAS/languages/<$this->_lang>.php
See also:
CAS_Client::_lang, CAS_Client::getString(), CAS_Client::setLang(), CAS_Client::getLang()
Definition at line 216 of file Client.php.