phpCAS: Miscellaneous
Miscellaneous
[Implementation]
Functions
CAS_Client::readURL ($url, &$headers, &$body, &$err_msg)
CAS_Client::buildSAMLPayload ()
CAS_Client::_curl_read_headers ($ch, $header)
CAS_Client::setURL ($url)
CAS_Client::getURL ()
CAS_Client::getServerUrl ()
CAS_Client::isHttps ()
CAS_Client::removeParameterFromQueryString ($parameterName, $queryString)
CAS_Client::buildQueryUrl ($url, $query)
CAS_Client::renameSession ($ticket)
CAS_Client::authError ($failure, $cas_url, $no_response, $bad_response='', $cas_response='', $err_code='', $err_msg='')
Variables
CAS_Client::$_curl_headers = array()
CAS_Client::$_url
$GLOBALS ['PHPCAS_CLIENT']
$GLOBALS ['PHPCAS_INIT_CALL']
$GLOBALS ['PHPCAS_AUTH_CHECK_CALL']
$GLOBALS ['PHPCAS_DEBUG']
Function Documentation
CAS_Client::_curl_read_headers ($ ch, $ header) [inherited]
This method is the callback used by readURL method to request HTTP headers.
Definition at line 2329 of file Client.php.
CAS_Client::authError ($ failure, $ cas_url, $ no_response, $ bad_response = '', $ cas_response = '', $ err_code = '', $ err_msg = '') [private, inherited]
This method is used to print the HTML output when the user was not authenticated.
Parameters:
$failure the failure that occured
$cas_url the URL the CAS server was asked for
$no_response the response from the CAS server (other parameters are ignored if TRUE)
$bad_response bad response from the CAS server ($err_code and $err_msg ignored if TRUE)
$cas_response the response of the CAS server
$err_code the error code given by the CAS server
$err_msg the error message given by the CAS server
Definition at line 3009 of file Client.php.
References $cas_url, phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceExit().
Referenced by CAS_Client::validateST().
CAS_Client::buildQueryUrl ($ url, $ query) [private, inherited]
This method is used to append query parameters to an url. Since the url might already contain parameter it has to be detected and to build a proper URL
Parameters:
$url base url to add the query params to
$query params in query form with & separated
Returns:
url with query params
Definition at line 2958 of file Client.php.
Referenced by CAS_Client::getServerLoginURL(), CAS_Client::getServerProxyValidateURL(), CAS_Client::getServerSamlValidateURL(), and CAS_Client::getServerServiceValidateURL().
CAS_Client::buildSAMLPayload () [private, inherited]
This method is used to build the SAML POST body sent to /samlValidate URL.
Returns:
the SOAP-encased SAMLP artifact (the ticket).
Definition at line 2312 of file Client.php.
References phpCAS::traceBegin(), and phpCAS::traceEnd().
CAS_Client::getServerUrl () [private, inherited]
Try to figure out the server URL with possible Proxys / Ports etc.
Returns:
Server URL with domain:port
Definition at line 2898 of file Client.php.
CAS_Client::getURL () [inherited]
This method returns the URL of the current request (without any ticket CGI parameter).
Returns:
The URL
Definition at line 2862 of file Client.php.
References phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceEnd().
Referenced by CAS_Client::getServerLoginURL(), CAS_Client::getServerProxyValidateURL(), CAS_Client::getServerSamlValidateURL(), CAS_Client::getServerServiceValidateURL(), and CAS_Client::isAuthenticated().
CAS_Client::isHttps () [private, inherited]
This method checks to see if the request is secured via HTTPS
Returns:
true if https, false otherwise
Definition at line 2927 of file Client.php.
Referenced by CAS_Client::__construct().
CAS_Client::readURL ($ url, &$ headers, &$ body, &$ err_msg) [private, inherited]
This method is used to acces a remote URL.
Parameters:
$url the URL to access.
$headers an array containing the HTTP header lines of the response (an empty array on failure).
$body the body of the response, as a string (empty on failure).
$err_msg an error message, filled on failure.
Returns:
TRUE on success, FALSE otherwise (in this later case, $err_msg contains an error message).
Definition at line 2264 of file Client.php.
References phpCAS::error().
Referenced by CAS_Client::validateST().
CAS_Client::removeParameterFromQueryString ($ parameterName, $ queryString) [private, inherited]
Removes a parameter from a query string
Parameters:
string $parameterName
string $queryString
Returns:
string
http://stackoverflow.com/questions/1842681/regular-expression-to-remove-one-parameter-from-query-string
Definition at line 2944 of file Client.php.
CAS_Client::renameSession ($ ticket) [private, inherited]
Renaming the session
Definition at line 2967 of file Client.php.
References phpCAS::error(), phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceEnd().
CAS_Client::setURL ($ url) [inherited]
This method sets the URL of the current request
Parameters:
$url url to set for service
Definition at line 2851 of file Client.php.
Variable Documentation
CAS_Client::$_curl_headers = array() [private, inherited]
Definition at line 2325 of file Client.php.
CAS_Client::$_url [private, inherited]
the URL of the current request (without any ticket CGI parameter). Written and read by CAS_Client::getURL().
Definition at line 2843 of file Client.php.
$GLOBALS['PHPCAS_AUTH_CHECK_CALL']
This global variable is used to store where the method checking the authentication is called from (to print comprehensive errors)
Definition at line 279 of file CAS.php.
$GLOBALS['PHPCAS_INIT_CALL']
This global variable is used to store where the initializer is called from (to print a comprehensive error in case of multiple calls).
Definition at line 266 of file CAS.php.
$GLOBALS['PHPCAS_CLIENT']
This global variable is used by the interface class phpCAS.
Definition at line 258 of file CAS.php.
$GLOBALS['PHPCAS_DEBUG']
This global variable is used to store phpCAS debug mode.
Definition at line 292 of file CAS.php.