phpCAS: CAS Proxy features (CAS 2.0, Proxy Granting Tickets)
CAS Proxy features (CAS 2.0, Proxy Granting Tickets)
[Implementation, CAS Basic client features (CAS 1.0, Service Tickets)]
Modules
PGT storage
Callback from the CAS server
Functions
CASClient::isProxy ()
CASClient::getPGT ()
CASClient::setPGT ($pgt)
CASClient::hasPGT ()
Variables
CASClient::$_proxy
CASClient::$_serviceCookieJar
CASClient::$_pgt
Function Documentation
CASClient::getPGT () [private, inherited]
This method returns the Proxy Granting Ticket given by the CAS server.
Returns:
The Proxy Granting Ticket.
Definition at line 1927 of file client.php.
Referenced by CASClient::isAuthenticated().
CASClient::hasPGT () [private, inherited]
This method tells if a Proxy Granting Ticket was stored.
Returns:
TRUE if a Proxy Granting Ticket has been stored.
Definition at line 1941 of file client.php.
CASClient::isProxy () [inherited]
Tells if a CAS client is a CAS proxy or not
Returns:
TRUE when the CAS client is a CAs proxy, FALSE otherwise
Definition at line 1901 of file client.php.
Referenced by CASClient::CASClient(), CASClient::isAuthenticated(), CASClient::validateST(), and CASClient::wasPreviouslyAuthenticated().
CASClient::setPGT ($ pgt) [private, inherited]
This method stores the Proxy Granting Ticket.
Parameters:
$pgt The Proxy Granting Ticket.
Definition at line 1934 of file client.php.
Referenced by CASClient::wasPreviouslyAuthenticated().
Variable Documentation
CASClient::$_pgt [private, inherited]
the Proxy Grnting Ticket given by the CAS server (empty otherwise). Written by CASClient::setPGT(), read by CASClient::getPGT() and CASClient::hasPGT().
Definition at line 1921 of file client.php.
CASClient::$_proxy [private, inherited]
A boolean telling if the client is a CAS proxy or not. Written by CASClient::CASClient(), read by CASClient::isProxy().
Definition at line 1889 of file client.php.
CASClient::$_serviceCookieJar [private, inherited]
Handler for managing service cookies.
Definition at line 1894 of file client.php.