phpCAS: Debugging
Debugging
[Implementation]
Functions
static phpCAS::backtrace ()
static phpCAS::log ($str)
static phpCAS::error ($msg)
static phpCAS::trace ($str)
static phpCAS::traceBegin ()
static phpCAS::traceEnd ($res= '')
static phpCAS::traceExit ()
Function Documentation
static phpCAS::backtrace () [static, inherited]
This method is a wrapper for debug_backtrace() that is not available in all PHP versions (>= 4.3.0 only)
Definition at line 487 of file CAS.php.
Referenced by phpCAS::checkAuthentication(), phpCAS::client(), phpCAS::error(), phpCAS::forceAuthentication(), CASClient::isAuthenticated(), phpCAS::proxy(), phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceEnd().
static phpCAS::error ($ msg) [static, inherited]
This method is used by interface methods to print an error and where the function was originally called from.
Parameters:
$msg the message to print
Definition at line 524 of file CAS.php.
References phpCAS::backtrace(), phpCAS::trace(), and phpCAS::traceExit().
Referenced by CAS_PGTStorage::__construct(), CAS_PGTStorageFile::__construct(), CASClient::callback(), CASClient::CASClient(), phpCAS::checkAuthentication(), phpCAS::client(), CAS_PGTStorageDb::createTable(), phpCAS::forceAuthentication(), CASClient::getAttributes(), phpCAS::getProxies(), phpCAS::getServerLogoutURL(), phpCAS::getServiceURL(), CAS_PGTStorage::getStorageInfo(), CAS_PGTStorage::getStorageType(), CASClient::getUser(), CASClient::handleLogoutRequests(), CAS_PGTStorageDb::init(), phpCAS::logout(), phpCAS::logoutWithRedirectService(), phpCAS::logoutWithRedirectServiceAndUrl(), phpCAS::logoutWithUrl(), phpCAS::proxy(), CAS_PGTStorage::read(), CASClient::readURL(), CASClient::renameSession(), phpCAS::retrievePT(), phpCAS::serviceMail(), phpCAS::serviceWeb(), phpCAS::setCacheTimesForAuthRecheck(), phpCAS::setCasServerCACert(), phpCAS::setDebug(), phpCAS::setExtraCurlOption(), phpCAS::setFixedCallbackURL(), phpCAS::setFixedServiceURL(), phpCAS::setHTMLFooter(), phpCAS::setHTMLHeader(), phpCAS::setLang(), phpCAS::setNoCasServerValidation(), CASClient::setPGTStorage(), phpCAS::setPGTStorage(), phpCAS::setPGTStorageDb(), phpCAS::setPGTStorageFile(), phpCAS::setPostAuthenticateCallback(), phpCAS::setServerLogoutURL(), phpCAS::setServerProxyValidateURL(), phpCAS::setServerSamlValidateURL(), phpCAS::setServerServiceValidateURL(), phpCAS::setSingleSignoutCallback(), CAS_PGTStorage::write(), CAS_PGTStorageFile::write(), and CAS_PGTStorageDb::write().
static phpCAS::log ($ str) [static, inherited]
Logs a string in debug mode.
Parameters:
$str the string to write
Definition at line 503 of file CAS.php.
Referenced by phpCAS::trace(), phpCAS::traceBegin(), phpCAS::traceEnd(), and phpCAS::traceExit().
static phpCAS::trace ($ str) [static, inherited]
This method is used to log something in debug mode.
Definition at line 549 of file CAS.php.
References phpCAS::backtrace(), and phpCAS::log().
Referenced by CAS_CurlRequest::_sendRequest(), CASClient::authError(), CASClient::callback(), CASClient::CASClient(), CASClient::checkAuthentication(), phpCAS::error(), CASClient::forceAuthentication(), phpCAS::forceAuthentication(), CASClient::handleLogoutRequests(), CASClient::isAuthenticated(), CASClient::logout(), CAS_CookieJar::parseCookieHeader(), CAS_PGTStorageFile::read(), CAS_PGTStorageDb::read(), CASClient::redirectToCas(), CASClient::renameSession(), CASClient::renewAuthentication(), CASClient::retrievePT(), CASClient::serviceWeb(), phpCAS::setDebug(), CASClient::setSessionAttributes(), CAS_CookieJar::storeCookies(), CASClient::validatePGT(), CASClient::validatePT(), CASClient::validateSA(), CASClient::validateST(), and CASClient::wasPreviouslyAuthenticated().
static phpCAS::traceBegin () [static, inherited]
This method is used to indicate the start of the execution of a function in debug mode.
Definition at line 557 of file CAS.php.
References phpCAS::backtrace(), and phpCAS::log().
Referenced by CAS_PGTStorage::__construct(), CAS_PGTStorageFile::__construct(), CAS_PGTStorageDb::__construct(), CAS_CurlRequest::_sendRequest(), CASClient::authError(), CASClient::buildSAMLPayload(), CASClient::callback(), CASClient::CASClient(), CASClient::checkAuthentication(), phpCAS::checkAuthentication(), phpCAS::client(), CAS_PGTStorageDb::createTable(), CASClient::forceAuthentication(), phpCAS::forceAuthentication(), CAS_PGTStorageFile::getPGTIouFilename(), CASClient::getServerLoginURL(), CASClient::getServerSamlValidateURL(), CASClient::handleLogoutRequests(), CAS_PGTStorageFile::init(), CAS_PGTStorageDb::init(), CASClient::isAuthenticated(), CASClient::logout(), phpCAS::logout(), phpCAS::logoutWithRedirectService(), phpCAS::logoutWithRedirectServiceAndUrl(), phpCAS::logoutWithUrl(), CAS_CookieJar::parseCookieHeaders(), phpCAS::proxy(), CAS_PGTStorageFile::read(), CAS_PGTStorageDb::read(), CASClient::readExtraAttributesCas20(), CASClient::redirectToCas(), CASClient::renameSession(), CASClient::renewAuthentication(), CASClient::retrievePT(), phpCAS::serviceMail(), CASClient::serviceWeb(), phpCAS::serviceWeb(), phpCAS::setCasServerCACert(), phpCAS::setExtraCurlOption(), phpCAS::setFixedCallbackURL(), phpCAS::setFixedServiceURL(), phpCAS::setNoCasServerValidation(), phpCAS::setPGTStorage(), phpCAS::setPGTStorageDb(), phpCAS::setPGTStorageFile(), phpCAS::setServerLogoutURL(), phpCAS::setServerProxyValidateURL(), phpCAS::setServerSamlValidateURL(), phpCAS::setServerServiceValidateURL(), CASClient::setSessionAttributes(), CASClient::validatePGT(), CASClient::validatePT(), CASClient::validateSA(), CASClient::validateST(), CASClient::wasPreviouslyAuthenticated(), CAS_PGTStorageFile::write(), and CAS_PGTStorageDb::write().
static phpCAS::traceEnd ($ res = '') [static, inherited]
This method is used to indicate the end of the execution of a function in debug mode.
Parameters:
$res the result of the function
Definition at line 592 of file CAS.php.
References phpCAS::backtrace(), and phpCAS::log().
Referenced by CAS_PGTStorage::__construct(), CAS_PGTStorageFile::__construct(), CAS_PGTStorageDb::__construct(), CAS_CurlRequest::_sendRequest(), CASClient::buildSAMLPayload(), CASClient::CASClient(), CASClient::checkAuthentication(), phpCAS::checkAuthentication(), phpCAS::client(), CAS_PGTStorageDb::createTable(), CASClient::forceAuthentication(), CAS_PGTStorageFile::getPGTIouFilename(), CASClient::getServerLoginURL(), CASClient::getServerSamlValidateURL(), CASClient::handleLogoutRequests(), CAS_PGTStorageFile::init(), CAS_PGTStorageDb::init(), CASClient::isAuthenticated(), phpCAS::logout(), phpCAS::logoutWithRedirectService(), phpCAS::logoutWithRedirectServiceAndUrl(), phpCAS::logoutWithUrl(), CAS_CookieJar::parseCookieHeaders(), phpCAS::proxy(), CAS_PGTStorageFile::read(), CAS_PGTStorageDb::read(), CASClient::readExtraAttributesCas20(), CASClient::renameSession(), CASClient::renewAuthentication(), CASClient::retrievePT(), phpCAS::serviceMail(), phpCAS::serviceWeb(), phpCAS::setCasServerCACert(), phpCAS::setExtraCurlOption(), phpCAS::setFixedCallbackURL(), phpCAS::setFixedServiceURL(), phpCAS::setNoCasServerValidation(), phpCAS::setPGTStorage(), phpCAS::setPGTStorageDb(), phpCAS::setPGTStorageFile(), phpCAS::setServerLogoutURL(), phpCAS::setServerProxyValidateURL(), phpCAS::setServerSamlValidateURL(), phpCAS::setServerServiceValidateURL(), CASClient::setSessionAttributes(), CASClient::validatePGT(), CASClient::wasPreviouslyAuthenticated(), CAS_PGTStorageFile::write(), and CAS_PGTStorageDb::write().
static phpCAS::traceExit () [static, inherited]
This method is used to indicate the end of the execution of the program
Definition at line 605 of file CAS.php.
References phpCAS::log().
Referenced by CASClient::authError(), CASClient::callback(), phpCAS::error(), CASClient::handleLogoutRequests(), CASClient::isAuthenticated(), CASClient::logout(), and CASClient::redirectToCas().