phpCAS: Configuration
Configuration
[Implementation]
Modules
HTML output
Internationalization
Functions
CASClient::getServerVersion ()
CASClient::getServerHostname ()
CASClient::getServerPort ()
CASClient::getServerURI ()
CASClient::getServerBaseURL ()
CASClient::getServerLoginURL ($gateway=false, $renew=false)
CASClient::setServerLoginURL ($url)
CASClient::setServerServiceValidateURL ($url)
CASClient::setServerProxyValidateURL ($url)
CASClient::setServerSamlValidateURL ($url)
CASClient::getServerServiceValidateURL ()
CASClient::getServerSamlValidateURL ()
CASClient::getServerProxyValidateURL ()
CASClient::getServerProxyURL ()
CASClient::getServerLogoutURL ()
CASClient::setServerLogoutURL ($url)
CASClient::setExtraCurlOption ($key, $value)
CASClient::setRequestImplementation ($className)
CASClient::isHttps ()
CASClient::CASClient ($server_version, $proxy, $server_hostname, $server_port, $server_uri, $start_session=true)
Variables
CASClient::$_server
CASClient::$_curl_options = array()
CASClient::$_requestImplementation = 'CAS_CurlRequest'
Function Documentation
CASClient::CASClient ($ server_version, $ proxy, $ server_hostname, $ server_port, $ server_uri, $ start_session = true) [inherited]
CASClient constructor.
Parameters:
$server_version the version of the CAS server
$proxy TRUE if the CAS client is a CAS proxy, FALSE otherwise
$server_hostname the hostname of the CAS server
$server_port the port the CAS server is running on
$server_uri the URI the CAS server is responding on
$start_session Have phpCAS start PHP sessions (default true)
Returns:
a newly created CASClient object
Definition at line 659 of file client.php.
References phpCAS::error(), CASClient::getServerVersion(), CASClient::isCallbackMode(), CASClient::isHttps(), CASClient::isLogoutRequest(), CASClient::isProxy(), CASClient::setCallbackMode(), phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceEnd().
CASClient::getServerBaseURL () [private, inherited]
This method is used to retrieve the base URL of the CAS server.
Returns:
a URL.
Definition at line 411 of file client.php.
Referenced by CASClient::getServerLoginURL(), CASClient::getServerLogoutURL(), CASClient::getServerProxyURL(), CASClient::getServerProxyValidateURL(), CASClient::getServerSamlValidateURL(), CASClient::getServerServiceValidateURL(), and CASClient::HTMLFilterOutput().
CASClient::getServerHostname () [private, inherited]
This method is used to retrieve the hostname of the CAS server.
Returns:
the hostname of the CAS server.
Definition at line 390 of file client.php.
Referenced by CASClient::handleLogoutRequests().
CASClient::getServerLoginURL ($ gateway = false, $ renew = false) [inherited]
This method is used to retrieve the login URL of the CAS server.
Parameters:
$gateway true to check authentication, false to force it
$renew true to force the authentication with the CAS server NOTE : It is recommended that CAS implementations ignore the "gateway" parameter if "renew" is set
Returns:
a URL.
Definition at line 433 of file client.php.
References CASClient::getServerBaseURL(), CASClient::getURL(), phpCAS::traceBegin(), and phpCAS::traceEnd().
Referenced by CASClient::redirectToCas().
CASClient::getServerLogoutURL () [inherited]
This method is used to retrieve the logout URL of the CAS server.
Returns:
a URL.
Definition at line 577 of file client.php.
References CASClient::getServerBaseURL().
Referenced by CASClient::logout().
CASClient::getServerPort () [private, inherited]
This method is used to retrieve the port of the CAS server.
Returns:
the port of the CAS server.
Definition at line 397 of file client.php.
CASClient::getServerProxyURL () [inherited]
This method is used to retrieve the proxy URL of the CAS server.
Returns:
a URL.
Definition at line 557 of file client.php.
References CASClient::getServerBaseURL(), and CASClient::getServerVersion().
CASClient::getServerProxyValidateURL () [inherited]
This method is used to retrieve the proxy validating URL of the CAS server.
Returns:
a URL.
Definition at line 537 of file client.php.
References CASClient::getServerBaseURL(), CASClient::getServerVersion(), and CASClient::getURL().
CASClient::getServerSamlValidateURL () [inherited]
This method is used to retrieve the SAML validating URL of the CAS server.
Returns:
a URL.
Definition at line 519 of file client.php.
References CASClient::getServerBaseURL(), CASClient::getServerVersion(), CASClient::getURL(), phpCAS::traceBegin(), and phpCAS::traceEnd().
CASClient::getServerServiceValidateURL () [inherited]
This method is used to retrieve the service validating URL of the CAS server.
Returns:
a URL.
Definition at line 500 of file client.php.
References CASClient::getServerBaseURL(), CASClient::getServerVersion(), and CASClient::getURL().
Referenced by CASClient::validateST().
CASClient::getServerURI () [private, inherited]
This method is used to retrieve the URI of the CAS server.
Returns:
a URI.
Definition at line 404 of file client.php.
CASClient::getServerVersion () [private, inherited]
This method is used to retrieve the version of the CAS server.
Returns:
the version of the CAS server.
Definition at line 381 of file client.php.
Referenced by CASClient::CASClient(), CASClient::getServerProxyURL(), CASClient::getServerProxyValidateURL(), CASClient::getServerSamlValidateURL(), CASClient::getServerServiceValidateURL(), and CASClient::HTMLFilterOutput().
CASClient::isHttps () [private, inherited]
This method checks to see if the request is secured via HTTPS
Returns:
true if https, false otherwise
Definition at line 636 of file client.php.
Referenced by CASClient::CASClient().
CASClient::setExtraCurlOption ($ key, $ value) [inherited]
This method is used to set additional user curl options.
Definition at line 604 of file client.php.
CASClient::setRequestImplementation ($ className) [inherited]
Override the default implementation used to make web requests in readUrl(). This class must implement the CAS_RequestInterface.
Parameters:
string $className
Returns:
void
Definition at line 624 of file client.php.
CASClient::setServerLoginURL ($ url) [inherited]
This method sets the login URL of the CAS server.
Parameters:
$url the login URL
Since:
0.4.21 by Wyman Chan
Definition at line 457 of file client.php.
CASClient::setServerLogoutURL ($ url) [inherited]
This method sets the logout URL of the CAS server.
Parameters:
$url the logout URL
Since:
0.4.21 by Wyman Chan
Definition at line 591 of file client.php.
CASClient::setServerProxyValidateURL ($ url) [inherited]
This method sets the proxyValidate URL of the CAS server.
Parameters:
$url the proxyValidate URL
Since:
1.1.0 by Joachim Fritschi
Definition at line 479 of file client.php.
CASClient::setServerSamlValidateURL ($ url) [inherited]
This method sets the samlValidate URL of the CAS server.
Parameters:
$url the samlValidate URL
Since:
1.1.0 by Joachim Fritschi
Definition at line 490 of file client.php.
CASClient::setServerServiceValidateURL ($ url) [inherited]
This method sets the serviceValidate URL of the CAS server.
Parameters:
$url the serviceValidate URL
Since:
1.1.0 by Joachim Fritschi
Definition at line 468 of file client.php.
Variable Documentation
CASClient::$_curl_options = array() [private, inherited]
An array to store extra curl options.
Definition at line 599 of file client.php.
CASClient::$_requestImplementation = 'CAS_CurlRequest' [private, inherited]
The class to instantiate for making web requests in readUrl(). The class specified must implement the CAS_RequestInterface. By default CAS_CurlRequest is used, but this may be overridden to supply alternate request mechanisms for testing.
Definition at line 615 of file client.php.
CASClient::$_server [private, inherited]
a record to store information about the CAS server.
$_server["version"]: the version of the CAS server
$_server["hostname"]: the hostname of the CAS server
$_server["port"]: the port the CAS server is running on
$_server["uri"]: the base URI the CAS server is responding on
$_server["base_url"]: the base URL of the CAS server
$_server["login_url"]: the login URL of the CAS server
$_server["service_validate_url"]: the service validating URL of the CAS server
$_server["proxy_url"]: the proxy URL of the CAS server
$_server["proxy_validate_url"]: the proxy validating URL of the CAS server
$_server["logout_url"]: the logout URL of the CAS server
$_server["version"], $_server["hostname"], $_server["port"] and $_server["uri"] are written by CASClient::CASClient(), read by CASClient::getServerVersion(), CASClient::getServerHostname(), CASClient::getServerPort() and CASClient::getServerURI().
The other fields are written and read by CASClient::getServerBaseURL(), CASClient::getServerLoginURL(), CASClient::getServerServiceValidateURL(), CASClient::getServerProxyValidateURL() and CASClient::getServerLogoutURL().
Definition at line 371 of file client.php.