phpCAS: PGT storage
PGT storage
[Configuration]
Enumerations
enum CAS_PGT_STORAGE_FILE_DEFAULT_PATH
enum CAS_PGT_STORAGE_FILE_FORMAT_PLAIN
enum CAS_PGT_STORAGE_FILE_FORMAT_XML
enum CAS_PGT_STORAGE_FILE_DEFAULT_FORMAT
Functions
static phpCAS::setPGTStorage ($storage)
static phpCAS::setPGTStorageDb ($dsn_or_pdo, $username='', $password='', $table='', $driver_options=null)
static phpCAS::setPGTStorageFile ($format= '', $path= '')
Enumeration Type Documentation
enum CAS_PGT_STORAGE_FILE_DEFAULT_FORMAT
Default format used when storing PGT's to file
Definition at line 162 of file CAS.php.
enum CAS_PGT_STORAGE_FILE_DEFAULT_PATH
Default path used when storing PGT's to file
Definition at line 150 of file CAS.php.
enum CAS_PGT_STORAGE_FILE_FORMAT_PLAIN
phpCAS::setPGTStorageFile()'s 2nd parameter to write plain text files
Definition at line 154 of file CAS.php.
enum CAS_PGT_STORAGE_FILE_FORMAT_XML
phpCAS::setPGTStorageFile()'s 2nd parameter to write xml files
Definition at line 158 of file CAS.php.
Function Documentation
static phpCAS::setPGTStorage ($ storage) [static, inherited]
This method can be used to set a custom PGT storage object.
Parameters:
$storage a PGT storage object that inherits from the CAS_PGTStorage class
Definition at line 716 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
static phpCAS::setPGTStorageDb ($ dsn_or_pdo, $ username = '', $ password = '', $ table = '', $ driver_options = null) [static, inherited]
This method is used to tell phpCAS to store the response of the CAS server to PGT requests in a database.
Parameters:
$dsn_or_pdo a dsn string to use for creating a PDO object or a PDO object
$username the username to use when connecting to the database
$password the password to use when connecting to the database
$table the table to use for storing and retrieving PGT's
$driver_options any driver options to use when connecting to the database
Definition at line 746 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
static phpCAS::setPGTStorageFile ($ format = '', $ path = '') [static, inherited]
This method is used to tell phpCAS to store the response of the CAS server to PGT requests onto the filesystem.
Parameters:
$format the format used to store the PGT's (`plain' and `xml' allowed)
$path the path where the PGT's should be stored
Examples:
example_file.php.
Definition at line 779 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().