phpCAS: CAS proxied client features (CAS 2.0, Proxy Tickets)
CAS proxied client features (CAS 2.0, Proxy Tickets)
[Implementation]
Functions
CAS_Client::getPT ()
CAS_Client::setPT ($pt)
CAS_Client::hasPT ()
CAS_Client::getProxies ()
CAS_Client::setProxies ($proxies)
CAS_Client::validatePT (&$validate_url, &$text_response, &$tree_response)
CAS_Client::readExtraAttributesCas20 ($success_elements)
CAS_Client::addAttributeToArray (array &$attributeArray, $name, $value)
Variables
CAS_Client::$_pt
CAS_Client::$_proxies = array()
Function Documentation
CAS_Client::addAttributeToArray (array &$ attributeArray, $ name, $ value) [private, inherited]
Add an attribute value to an array of attributes.
Parameters:
ref array $array
string $name
string $value
Returns:
void
Definition at line 2806 of file Client.php.
CAS_Client::getProxies () [inherited]
Answer an array of proxies that are sitting in front of this application.
This method will only return a non-empty array if we have received and validated a Proxy Ticket.
Returns:
array public
Since:
6/25/09
Definition at line 2550 of file Client.php.
CAS_Client::getPT () [inherited]
This method returns the Proxy Ticket provided in the URL of the request.
Returns:
The proxy ticket.
Definition at line 2509 of file Client.php.
Referenced by CAS_Client::isAuthenticated().
CAS_Client::hasPT () [inherited]
This method tells if a Proxy Ticket was stored.
Returns:
TRUE if a Proxy Ticket has been stored.
Definition at line 2526 of file Client.php.
Referenced by CAS_Client::isAuthenticated().
CAS_Client::readExtraAttributesCas20 ($ success_elements) [private, inherited]
This method will parse the DOM and pull out the attributes from the XML payload and put them into an array, then put the array into the session.
Parameters:
$text_response the XML payload.
Returns:
bool TRUE when successfull, halt otherwise by calling CAS_Client::authError().
Definition at line 2690 of file Client.php.
Referenced by CAS_Client::validateST().
CAS_Client::setProxies ($ proxies) [private, inherited]
Set the Proxy array, probably from persistant storage.
Parameters:
array $proxies
Returns:
void private
Since:
6/25/09
Definition at line 2562 of file Client.php.
Referenced by CAS_Client::wasPreviouslyAuthenticated().
CAS_Client::setPT ($ pt) [inherited]
This method stores the Proxy Ticket.
Parameters:
$pt The Proxy Ticket.
Definition at line 2519 of file Client.php.
Referenced by CAS_Client::wasPreviouslyAuthenticated().
CAS_Client::validatePT (&$ validate_url, &$ text_response, &$ tree_response) [inherited]
This method is used to validate a ST or PT; halt on failure Used for all CAS 2.0 validations
Returns:
bool TRUE when successfull, halt otherwise by calling CAS_Client::authError().
Definition at line 2581 of file Client.php.
References phpCAS::trace(), and phpCAS::traceBegin().
Referenced by CAS_Client::isAuthenticated().
Variable Documentation
CAS_Client::$_proxies = array() [private, inherited]
This array will store a list of proxies in front of this application. This property will only be populated if this script is being proxied rather than accessed directly.
It is set in CAS_Client::validatePT() and can be read by CAS_Client::getProxies() private
Definition at line 2538 of file Client.php.
CAS_Client::$_pt [private, inherited]
the Proxy Ticket provided in the URL of the request if present (empty otherwise). Written by CAS_Client::CAS_Client(), read by CAS_Client::getPT() and CAS_Client::hasPGT().
Definition at line 2503 of file Client.php.