phpCAS: CAS SAML features (SAML 1.1)
CAS SAML features (SAML 1.1)
[Implementation]
Functions
CAS_Client::validateSA ($validate_url, &$text_response, &$tree_response)
CAS_Client::setSessionAttributes ($text_response)
CAS_Client::getSA ()
CAS_Client::setSA ($sa)
CAS_Client::hasSA ()
Function Documentation
CAS_Client::getSA () [inherited]
This method returns the SAML Ticket provided in the URL of the request.
Returns:
The SAML ticket.
Definition at line 1760 of file Client.php.
Referenced by CAS_Client::isAuthenticated().
CAS_Client::hasSA () [inherited]
This method tells if a SAML Ticket was stored.
Returns:
TRUE if a SAML Ticket has been stored.
Definition at line 1774 of file Client.php.
Referenced by CAS_Client::isAuthenticated().
CAS_Client::setSA ($ sa) [inherited]
This method stores the SAML Ticket.
Parameters:
$sa The SAML Ticket.
Definition at line 1767 of file Client.php.
CAS_Client::setSessionAttributes ($ text_response) [private, inherited]
This method will parse the DOM and pull out the attributes from the SAML payload and put them into an array, then put the array into the session.
Parameters:
$text_response the SAML payload.
Returns:
bool TRUE when successfull and FALSE if no attributes a found
Definition at line 1707 of file Client.php.
References phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceEnd().
CAS_Client::validateSA ($ validate_url, &$ text_response, &$ tree_response) [inherited]
This method is used to validate a SAML TICKET; halt on failure, and sets $validate_url, $text_reponse and $tree_response on success. These parameters are used later by CAS_Client::validatePGT() for CAS proxies.
Parameters:
$validate_url the URL of the request to the CAS server.
$text_response the response of the CAS server, as is (XML text).
$tree_response the response of the CAS server, as a DOM XML tree.
Returns:
bool TRUE when successfull, halt otherwise by calling CAS_Client::authError().
Definition at line 1626 of file Client.php.
References phpCAS::trace(), and phpCAS::traceBegin().