phpCAS: PGT storage
PGT storage
[CAS Proxy features (CAS 2.0, Proxy Granting Tickets), CAS Basic client features (CAS 1.0, Service Tickets)]
Classes
class PGTStorage
Modules
PGT storage in a database
PGT storage on the filesystem
Functions
CASClient::initPGTStorage ()
CASClient::storePGT ($pgt, $pgt_iou)
CASClient::loadPGT ($pgt_iou)
CASClient::setPGTStorage ($storage)
CASClient::setPGTStorageDb ($dsn_or_pdo, $username='', $password='', $table='', $driver_options=null)
CASClient::setPGTStorageFile ($format='', $path='')
CASClient::validatePGT (&$validate_url, $text_response, $tree_response)
CASClient::retrievePT ($target_service, &$err_code, &$err_msg)
CASClient::readURL ($url, array $cookies, &$headers, &$body, &$err_msg)
CASClient::buildSAMLPayload ()
CASClient::_curl_read_headers ($ch, $header)
CASClient::serviceWeb ($url, &$err_code, &$output)
CASClient::serviceMail ($url, $service, $flags, &$err_code, &$err_msg, &$pt)
CAS_PGTStorage::__construct ($cas_parent)
CAS_PGTStorage::getStorageType ()
CAS_PGTStorage::getStorageInfo ()
CAS_PGTStorage::setErrorMessage ($error_message)
CAS_PGTStorage::getErrorMessage ()
CAS_PGTStorage::isInitialized ()
CAS_PGTStorage::init ()
CAS_PGTStorage::write ($pgt, $pgt_iou)
CAS_PGTStorage::read ($pgt_iou)
Variables
CASClient::$_pgt_storage
CASClient::$_curl_headers = array()
CAS_PGTStorage::$_error_message
CAS_PGTStorage::$_initialized
Function Documentation
CAS_PGTStorage::__construct ($ cas_parent) [protected, inherited]
The constructor of the class, should be called only by inherited classes.
Parameters:
$cas_parent the CASclient instance that creates the current object.
Definition at line 63 of file pgt-main.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
CASClient::_curl_read_headers ($ ch, $ header) [inherited]
This method is the callback used by readURL method to request HTTP headers.
Definition at line 2430 of file client.php.
CASClient::buildSAMLPayload () [private, inherited]
This method is used to build the SAML POST body sent to /samlValidate URL.
Returns:
the SOAP-encased SAMLP artifact (the ticket).
Definition at line 2413 of file client.php.
References phpCAS::traceBegin(), and phpCAS::traceEnd().
CAS_PGTStorage::getErrorMessage () [inherited]
This method returns an error message set by PGTStorage::setErrorMessage().
Returns:
an error message when set by PGTStorage::setErrorMessage(), FALSE otherwise.
Deprecated:
not used.
Definition at line 135 of file pgt-main.php.
CAS_PGTStorage::getStorageInfo () [inherited]
This virtual method returns an informational string giving informations on the parameters of the storage.(used for debugging purposes).
Reimplemented in CAS_PGTStorageDb, and CAS_PGTStorageFile.
Definition at line 93 of file pgt-main.php.
References phpCAS::error().
CAS_PGTStorage::getStorageType () [inherited]
This virtual method returns an informational string giving the type of storage used by the object (used for debugging purposes).
Reimplemented in CAS_PGTStorageDb, and CAS_PGTStorageFile.
Definition at line 82 of file pgt-main.php.
References phpCAS::error().
CAS_PGTStorage::init () [protected, inherited]
This virtual method initializes the object.
Reimplemented in CAS_PGTStorageDb, and CAS_PGTStorageFile.
Definition at line 170 of file pgt-main.php.
CASClient::initPGTStorage () [private, inherited]
This method is used to initialize the storage of PGT's. Halts on error.
Definition at line 2092 of file client.php.
CAS_PGTStorage::isInitialized () [protected, inherited]
This method tells if the storage has already been intialized.
Returns:
a boolean
Definition at line 160 of file pgt-main.php.
Referenced by CAS_PGTStorageFile::init(), and CAS_PGTStorageDb::init().
CASClient::loadPGT ($ pgt_iou) [private, inherited]
This method reads a PGT from its Iou and deletes the corresponding storage entry.
Parameters:
$pgt_iou the PGT Iou
Returns:
The PGT corresponding to the Iou, FALSE when not found.
Definition at line 2124 of file client.php.
CAS_PGTStorage::read ($ pgt_iou) [protected, inherited]
This virtual method reads a PGT corresponding to a PGT Iou and deletes the corresponding storage entry.
Note:
Should never be called.
Parameters:
$pgt_iou the PGT iou
Reimplemented in CAS_PGTStorageDb, and CAS_PGTStorageFile.
Definition at line 202 of file pgt-main.php.
References phpCAS::error().
CASClient::readURL ($ url, array $ cookies, &$ headers, &$ body, &$ err_msg) [private, inherited]
This method is used to acces a remote URL.
Parameters:
$url the URL to access.
$cookies an array containing cookies strings such as 'name=val'
$headers an array containing the HTTP header lines of the response (an empty array on failure).
$body the body of the response, as a string (empty on failure).
$err_msg an error message, filled on failure.
Returns:
TRUE on success, FALSE otherwise (in this later case, $err_msg contains an error message).
Definition at line 2364 of file client.php.
References phpCAS::error().
Referenced by CASClient::validateST().
CASClient::retrievePT ($ target_service, &$ err_code, &$ err_msg) [private, inherited]
This method is used to retrieve PT's from the CAS server thanks to a PGT.
Parameters:
$target_service the service to ask for with the PT.
$err_code an error code (PHPCAS_SERVICE_OK on success).
$err_msg an error message (empty on success).
Returns:
a Proxy Ticket, or FALSE on error.
Definition at line 2249 of file client.php.
References phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceEnd().
CASClient::serviceMail ($ url, $ service, $ flags, &$ err_code, &$ err_msg, &$ pt) [inherited]
This method is used to access an IMAP/POP3/NNTP service.
Parameters:
$url a string giving the URL of the service, including the mailing box for IMAP URLs, as accepted by imap_open().
$service a string giving for CAS retrieve Proxy ticket
$flags options given to imap_open().
$err_code an error code Possible values are PHPCAS_SERVICE_OK (on success), PHPCAS_SERVICE_PT_NO_SERVER_RESPONSE, PHPCAS_SERVICE_PT_BAD_SERVER_RESPONSE, PHPCAS_SERVICE_PT_FAILURE, PHPCAS_SERVICE_NOT_AVAILABLE.
$err_msg an error message on failure
$pt the Proxy Ticket (PT) retrieved from the CAS server to access the URL on success, FALSE on error).
Returns:
an IMAP stream on success, FALSE otherwise (in this later case, $err_code gives the reason why it failed and $err_msg contains an error message).
Definition at line 2541 of file client.php.
CASClient::serviceWeb ($ url, &$ err_code, &$ output) [inherited]
This method is used to access an HTTP[S] service.
Parameters:
$url the service to access.
$err_code an error code Possible values are PHPCAS_SERVICE_OK (on success), PHPCAS_SERVICE_PT_NO_SERVER_RESPONSE, PHPCAS_SERVICE_PT_BAD_SERVER_RESPONSE, PHPCAS_SERVICE_PT_FAILURE, PHPCAS_SERVICE_NOT_AVAILABLE.
$output the output of the service (also used to give an error message on failure).
Returns:
TRUE on success, FALSE otherwise (in this later case, $err_code gives the reason why it failed and $output contains an error message).
Definition at line 2449 of file client.php.
References phpCAS::trace(), and phpCAS::traceBegin().
CAS_PGTStorage::setErrorMessage ($ error_message) [protected, inherited]
This method sets en error message, which can be read later by PGTStorage::getErrorMessage().
Parameters:
$error_message an error message
Deprecated:
not used.
Definition at line 121 of file pgt-main.php.
CASClient::setPGTStorage ($ storage) [inherited]
This method can be used to set a custom PGT storage object.
Parameters:
$storage a PGT storage object that inherits from the CAS_PGTStorage class
Definition at line 2137 of file client.php.
References phpCAS::error().
CASClient::setPGTStorageDb ($ dsn_or_pdo, $ username = '', $ password = '', $ table = '', $ driver_options = null) [inherited]
This method is used to tell phpCAS to store the response of the CAS server to PGT requests in a database.
Parameters:
$dsn_or_pdo a dsn string to use for creating a PDO object or a PDO object
$username the username to use when connecting to the database
$password the password to use when connecting to the database
$table the table to use for storing and retrieving PGT's
$driver_options any driver options to use when connecting to the database
Definition at line 2163 of file client.php.
CASClient::setPGTStorageFile ($ format = '', $ path = '') [inherited]
This method is used to tell phpCAS to store the response of the CAS server to PGT requests onto the filesystem.
Parameters:
$format the format used to store the PGT's (`plain' and `xml' allowed)
$path the path where the PGT's should be stored
Definition at line 2176 of file client.php.
CASClient::storePGT ($ pgt, $ pgt_iou) [private, inherited]
This method stores a PGT. Halts on error.
Parameters:
$pgt the PGT to store
$pgt_iou its corresponding Iou
Definition at line 2109 of file client.php.
CASClient::validatePGT (&$ validate_url, $ text_response, $ tree_response) [private, inherited]
This method is used to validate a PGT; halt on failure.
Parameters:
$validate_url the URL of the request to the CAS server.
$text_response the response of the CAS server, as is (XML text); result of CASClient::validateST() or CASClient::validatePT().
$tree_response the response of the CAS server, as a DOM XML tree; result of CASClient::validateST() or CASClient::validatePT().
Returns:
bool TRUE when successfull, halt otherwise by calling CASClient::authError().
Definition at line 2198 of file client.php.
References phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceEnd().
Referenced by CASClient::isAuthenticated().
CAS_PGTStorage::write ($ pgt, $ pgt_iou) [protected, inherited]
This virtual method stores a PGT and its corresponding PGT Iuo.
Note:
Should never be called.
Parameters:
$pgt the PGT
$pgt_iou the PGT iou
Reimplemented in CAS_PGTStorageDb, and CAS_PGTStorageFile.
Definition at line 188 of file pgt-main.php.
References phpCAS::error().
Variable Documentation
CASClient::$_curl_headers = array() [private, inherited]
Definition at line 2426 of file client.php.
CAS_PGTStorage::$_error_message [private, inherited]
string used to store an error message. Written by PGTStorage::setErrorMessage(), read by PGTStorage::getErrorMessage().
Deprecated:
not used.
Definition at line 110 of file pgt-main.php.
CAS_PGTStorage::$_initialized [private, inherited]
a boolean telling if the storage has already been initialized. Written by PGTStorage::init(), read by PGTStorage::isInitialized().
Definition at line 151 of file pgt-main.php.
CASClient::$_pgt_storage [private, inherited]
an instance of a class inheriting of PGTStorage, used to deal with PGT storage. Created by CASClient::setPGTStorageFile(), used by CASClient::setPGTStorageFile() and CASClient::initPGTStorage().
Definition at line 2086 of file client.php.