phpCAS: Initialization
Initialization
[User interface]
Functions
static phpCAS::client ($server_version, $server_hostname, $server_port, $server_uri, $start_session=true)
static phpCAS::proxy ($server_version, $server_hostname, $server_port, $server_uri, $start_session=true)
Function Documentation
static phpCAS::client ($ server_version, $ server_hostname, $ server_port, $ server_uri, $ start_session = true) [static, inherited]
phpCAS client initializer.
Note:
Only one of the phpCAS::client() and phpCAS::proxy functions should be called, only once, and before all other methods (except phpCAS::getVersion() and phpCAS::setDebug()).
Parameters:
$server_version the version of the CAS server
$server_hostname the hostname of the CAS server
$server_port the port the CAS server is running on
$server_uri the URI the CAS server is responding on
$start_session Have phpCAS start PHP sessions (default true)
Returns:
a newly created CAS_Client object
Examples:
example_advanced_saml11.php, example_custom_urls.php, example_gateway.php, example_html.php, example_lang.php, example_logout.php, example_service.php, example_service_POST.php, and example_simple.php.
Definition at line 348 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
static phpCAS::proxy ($ server_version, $ server_hostname, $ server_port, $ server_uri, $ start_session = true) [static, inherited]
phpCAS proxy initializer.
Note:
Only one of the phpCAS::client() and phpCAS::proxy functions should be called, only once, and before all other methods (except phpCAS::getVersion() and phpCAS::setDebug()).
Parameters:
$server_version the version of the CAS server
$server_hostname the hostname of the CAS server
$server_port the port the CAS server is running on
$server_uri the URI the CAS server is responding on
$start_session Have phpCAS start PHP sessions (default true)
Returns:
a newly created CAS_Client object
Examples:
example_pgt_storage_file.php, example_proxy_GET.php, example_proxy_POST.php, example_proxy_serviceWeb.php, example_proxy_serviceWeb_chaining.php, and example_service_that_proxies.php.
Definition at line 397 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().