phpCAS: CAS Basic client features (CAS 1.0, Service Tickets)
CAS Basic client features (CAS 1.0, Service Tickets)
[Implementation]
Modules
CAS Proxy features (CAS 2.0, Proxy Granting Tickets)
Callback from the CAS server
PGT storage
CAS proxied client features (CAS 2.0, Proxy Tickets)
Miscellaneous
Functions
CASClient::getST ()
CASClient::setST ($st)
CASClient::hasST ()
CASClient::setCasServerCACert ($cert)
CASClient::setNoCasServerValidation ()
CASClient::validateST ($validate_url, &$text_response, &$tree_response)
CASClient::readExtraAttributesCas20 ($success_elements)
CASClient::addAttributeToArray (array &$attributeArray, $name, $value)
CASClient::validateSA ($validate_url, &$text_response, &$tree_response)
CASClient::setSessionAttributes ($text_response)
Variables
CASClient::$_st
CASClient::$_cas_server_ca_cert
CASClient::$_no_cas_server_validation
Function Documentation
CASClient::addAttributeToArray (array &$ attributeArray, $ name, $ value) [private, inherited]
Add an attribute value to an array of attributes.
Parameters:
ref array $array
string $name
string $value
Returns:
void
Definition at line 1705 of file client.php.
CASClient::getST () [inherited]
This method returns the Service Ticket provided in the URL of the request.
Returns:
The service ticket.
Definition at line 1395 of file client.php.
Referenced by CASClient::isAuthenticated(), and CASClient::validateST().
CASClient::hasST () [inherited]
This method tells if a Service Ticket was stored.
Returns:
TRUE if a Service Ticket has been stored.
Definition at line 1409 of file client.php.
Referenced by CASClient::isAuthenticated().
CASClient::readExtraAttributesCas20 ($ success_elements) [private, inherited]
This method will parse the DOM and pull out the attributes from the XML payload and put them into an array, then put the array into the session.
Parameters:
$text_response the XML payload.
Returns:
bool TRUE when successfull, halt otherwise by calling CASClient::authError().
Definition at line 1589 of file client.php.
References phpCAS::traceBegin(), and phpCAS::traceEnd().
Referenced by CASClient::validateST().
CASClient::setCasServerCACert ($ cert) [inherited]
Set the CA certificate of the CAS server.
Parameters:
$cert the PEM certificate of the CA that emited the cert of the server
Definition at line 1442 of file client.php.
CASClient::setNoCasServerValidation () [inherited]
Set no SSL validation for the CAS server.
Definition at line 1450 of file client.php.
CASClient::setSessionAttributes ($ text_response) [private, inherited]
This method will parse the DOM and pull out the attributes from the SAML payload and put them into an array, then put the array into the session.
Parameters:
$text_response the SAML payload.
Returns:
bool TRUE when successfull and FALSE if no attributes a found
Definition at line 1820 of file client.php.
References phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceEnd().
CASClient::setST ($ st) [inherited]
This method stores the Service Ticket.
Parameters:
$st The Service Ticket.
Definition at line 1402 of file client.php.
Referenced by CASClient::wasPreviouslyAuthenticated().
CASClient::validateSA ($ validate_url, &$ text_response, &$ tree_response) [inherited]
This method is used to validate a SAML TICKET; halt on failure, and sets $validate_url, $text_reponse and $tree_response on success. These parameters are used later by CASClient::validatePGT() for CAS proxies.
Parameters:
$validate_url the URL of the request to the CAS server.
$text_response the response of the CAS server, as is (XML text).
$tree_response the response of the CAS server, as a DOM XML tree.
Returns:
bool TRUE when successfull, halt otherwise by calling CASClient::authError().
Definition at line 1739 of file client.php.
References phpCAS::trace(), and phpCAS::traceBegin().
CASClient::validateST ($ validate_url, &$ text_response, &$ tree_response) [inherited]
This method is used to validate a ST; halt on failure, and sets $validate_url, $text_reponse and $tree_response on success. These parameters are used later by CASClient::validatePGT() for CAS proxies. Used for all CAS 1.0 validations
Parameters:
$validate_url the URL of the request to the CAS server.
$text_response the response of the CAS server, as is (XML text).
$tree_response the response of the CAS server, as a DOM XML tree.
Returns:
bool TRUE when successfull, halt otherwise by calling CASClient::authError().
Definition at line 1466 of file client.php.
References CASClient::authError(), CASClient::getCallbackURL(), CASClient::getServerServiceValidateURL(), CASClient::getST(), CASClient::isProxy(), CASClient::readExtraAttributesCas20(), CASClient::readURL(), CASClient::setUser(), phpCAS::trace(), and phpCAS::traceBegin().
Variable Documentation
CASClient::$_cas_server_ca_cert [private, inherited]
the certificate of the CAS server CA.
Definition at line 1427 of file client.php.
CASClient::$_no_cas_server_validation [private, inherited]
Set to true not to validate the CAS server.
Definition at line 1434 of file client.php.
CASClient::$_st [private, inherited]
the Service Ticket provided in the URL of the request if present (empty otherwise). Written by CASClient::CASClient(), read by CASClient::getST() and CASClient::hasPGT().
Definition at line 1389 of file client.php.