phpCAS: CAS_RequestInterface Interface Reference
CAS_RequestInterface Interface Reference