<?php
/*
      +----------------------------------------------------------------------+
      | CLAROLINE version 1.3.0 $Revision$                            |
      +----------------------------------------------------------------------+
      | Copyright (c) 2001, 2002 Universite catholique de Louvain (UCL)      |
      +----------------------------------------------------------------------+
      |   $Id$             |
      |   English Translation                                                |
      +----------------------------------------------------------------------+
      |   This program is free software; you can redistribute it and/or      |
      |   modify it under the terms of the GNU General Public License        |
      |   as published by the Free Software Foundation; either version 2     |
      |   of the License, or (at your option) any later version.             |
      |                                                                      |
      |   This program is distributed in the hope that it will be useful,    |
      |   but WITHOUT ANY WARRANTY; without even the implied warranty of     |
      |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the      |
      |   GNU General Public License for more details.                       |
      |                                                                      |
      |   You should have received a copy of the GNU General Public License  |
      |   along with this program; if not, write to the Free Software        |
      |   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA          |
      |   02111-1307, USA. The GNU GPL license is also available through     |
      |   the world-wide-web at http://www.gnu.org/copyleft/gpl.html         |
      +----------------------------------------------------------------------+
      | Authors: Thomas Depraetere <depraetere@ipm.ucl.ac.be>                |
      |          Hugues Peeters    <peeters@ipm.ucl.ac.be>                   |
      |          Christophe Geschι <gesche@ipm.ucl.ac.be>                    |
      +----------------------------------------------------------------------+
      | Translator :                                                         |
      |          Thomas Depraetere <depraetere@ipm.ucl.ac.be>                |
      |          Andrew Lynn       <Andrew.Lynn@strath.ac.uk>                |
      +----------------------------------------------------------------------+
 */

$langInvalidId = '<font color="red" size="1" face="arial, helvetica">
        Λάθος στοιχεία.<br>Αν δεν είστε γραμμένος, συμπληρώστε τη
        <a href=modules/auth/newuser_info.php>φόρμα εγγραφής</a>.
        </font><br>&nbsp;<br>';
$langMyCourses="Τα μαθήματά μου";
$langMyCoursesProf="Τα μαθήματα που υποστηρίζω (Καθηγητής)";
$langMyCoursesUser="Τα μαθήματα που παρακολουθώ (Εγγεγραμμένος)";

$langNoCourses="Δεν υπάρχουν μαθήματα";

$langCourseCreate="Δημιουργία μαθήματος";
$langModifyProfile="Αλλαγή του προφίλ μου";
$langMyAgenda = "Το Ημερολόγιό μου";
$langMyAnnouncements = "Οι Ανακοινώσεις μου";
$langWelcome="τα μαθήματα είναι διαθέσιμα παρακάτω. Άλλα μαθήματα απαιτούν 
όνομα χρήστη και συνθηματικό, τα οποία μπορείτε να τα αποκτήσετε κάνοντας κλίκ στην 'εγγραφή'. Οι καθηγητές
μπορούν να δημιουργήσουν μαθήματα κάνοντας κλικ στην εγγραφή επίσης, αλλά επιλέγοντας ύστερα 
'Δημιουργία μαθημάτων (καθηγητές)'.";
$langAdminTool = "Εργαλεία Διαχείρισης";
$langUserName="Όνομα χρήστη (username)";
$langPass="Συνθηματικό (password)";
$langEnter="Είσοδος";
$langHelp="Βοήθεια";
$langManager="Διαχειριστής";
$langManagement="Διαχείριση";
$langPlatform="Powered by";
$langReg="Εγγραφή";
$langMenu ="Μενού";
$langLogout="Έξοδος";
$langOtherCourses="Εγγραφή σε μάθημα";
$langSupportForum="Περιοχή Υποστήριξης";
$langNewUser = 'Εγγραφή Χρήστη';
$langProfReq = 'Εγγραφή Καθηγητή';
$langUser = 'Χρήστης:';
$langManuals = 'Εγχειρίδια';
$langContact = 'Επικοινωνία';
$langInfoPlat = 'Ταυτότητα Πλατφόρμας';
$lang_forgot_pass = "Ξεχάσατε το συνθηματικό σας;";
$langNewAnnounce = "Νέα !";
$langUnregUser = "Διαγραφή λογαριασμού";
$langListFaculte = "Κατάλογος Μαθημάτων";
$langAsynchronous = "Ομάδα Ασύγχρονης Τηλεκπαίδευσης";
$langCopyright = "Πληροφορίες Πνευματικών Δικαιωμάτων";
$langUserLogin = "Σύνδεση χρήστη";
$langWelcomeToEclass = "Καλωσορίσατε στο e-Class!";

$langSearch = "Αναζήτηση";

$langPlatformAnnounce = "Ανακοινώσεις";
$langInfo = "Η πλατφόρμα <strong>GUnet e-Class</strong> αποτελεί ένα ολοκληρωμένο σύστημα ηλεκτρονικής οργάνωσης, αποθήκευσης και παρουσίασης ηλεκτρονικού εκπαιδευτικού υλικού. Είναι σχεδιασμένη με προσανατολισμό την ενίσχυση και υποστήριξη της εκπαιδευτικής διαδικασίας, προσφέροντας στους συμμετέχοντες ένα δυναμικό περιβάλλον αλληλεπίδρασης, ανεξάρτητο από τους περιοριστικούς παράγοντες του χώρου και του χρόνου της κλασσικής διδασκαλίας.";

?>
