name: PHPCS

on:
  # push:
  #   branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.5, 8.4, 8.3]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=phpcs.xml .